import { Activity, Database, HeartPulse, ShieldCheck } from "lucide-react";
import ResearchLayout from "@/components/ResearchLayout";
import { CohortBars, DetailDisclosure, NextPage, PageIntro, PaperCard, SectionLabel } from "@/components/ResearchPrimitives";

export default function Data() {
  return <ResearchLayout><div className="wide-wrap page-wrap"><PageIntro index="04" eyebrow="The data" title="292 patients. Four diagnostic classes. Real hospital data." description="Cardiac MRI and structured clinical records from Hospital Sant Pau form a deliberately difficult differential diagnosis cohort: imbalanced, clinically specific, and small enough to punish careless modelling."><div className="intro-meta"><span>HOSPITAL SANT PAU</span><span>N = 292</span><span>25 FEATURES</span></div></PageIntro>
    <section className="page-section" data-testid="data-cohort-section"><div className="data-overview-grid"><PaperCard className="cohort-card-large" testId="data-cohort-card"><div className="card-topline"><span>COHORT COMPOSITION</span><span className="mono-tag">N = 292</span></div><h2>Diagnostic class counts</h2><CohortBars /><div className="cohort-legend"><span><i className="legend-dot teal" />HCMP · genetic</span><span><i className="legend-dot mint" />mimic / control classes</span></div></PaperCard><div className="data-stat-stack" data-testid="data-stat-stack">{[{ icon: HeartPulse, number: "165", label: "HCMP", description: "genetic hypertrophic cardiomyopathy" }, { icon: Activity, number: "66 / 37 / 24", label: "Other classes", description: "hypertensive HCM / Normal / Amyloidosis" }, { icon: Database, number: "25", label: "Features", description: "imaging, demographics, comorbidities, history" }].map(({ icon: Icon, number, label, description }) => <PaperCard key={label} testId={`data-stat-${label.toLowerCase().replace(/\s/g, "-")}`}><Icon size={18} /><strong>{number}</strong><span>{label}</span><p>{description}</p></PaperCard>)}</div></div></section>
    <section className="page-section" data-testid="data-mri-section"><SectionLabel index="04.0">Representative imaging</SectionLabel><PaperCard className="research-figure-card data-mri-card" testId="data-mri-figure-card"><figure><img className="research-image" src="/assets/figD2_ED_vs_ES_per_class.png" alt="Sant Pau cardiac MRI end-diastole and end-systole examples across pathology classes" loading="lazy" /><figcaption><span>FIG. 04A</span><strong>End-diastole vs end-systole, middle slice</strong><small>One representative patient per pathology class: Normal, HCMP, HCM, and amyloidosis.</small></figcaption></figure></PaperCard></section>
    <section className="page-section" data-testid="data-feature-section"><SectionLabel index="04.1">Feature design</SectionLabel><div className="feature-columns"><PaperCard testId="data-feature-card"><h3>What the model can use</h3><div className="feature-group"><span>IMAGING</span><p>LV / RV volumes, wall thickness, mass index</p></div><div className="feature-group"><span>DEMOGRAPHICS</span><p>Age, sex, BMI, body surface area</p></div><div className="feature-group"><span>COMORBIDITIES</span><p>Dyslipidaemia, diabetes, atrial fibrillation</p></div><div className="feature-group"><span>HISTORY</span><p>Family history, heart-failure admissions, NYHA class, ICD / pacemaker</p></div></PaperCard><PaperCard className="excluded-card" testId="data-excluded-card"><div className="excluded-icon"><ShieldCheck size={19} /></div><h3>Excluded by design</h3><p>Hypertension status and LGE presence were deliberately left out as predictors. Both are too circularly tied to the outcome labels to serve as independent clinical signal.</p><div className="exclusion-rule"><span>INDEPENDENCE</span><strong>preserved</strong></div></PaperCard></div></section>
    <section className="page-section" data-testid="data-preprocessing-section"><SectionLabel index="04.2">Preprocessing protocol</SectionLabel><div className="preprocess-grid"><div className="preprocess-step"><span>01</span><strong>Segment</strong><p>Use segmentation masks to identify the LV cavity across the cardiac cycle.</p></div><div className="preprocess-step"><span>02</span><strong>Select frames</strong><p>Re-derive ED and ES as max/min LV cavity volume, not an intensity heuristic.</p></div><div className="preprocess-step"><span>03</span><strong>Evaluate</strong><p>Validate physiological consistency on manual review, then carry into five folds.</p></div></div><DetailDisclosure title="Why frame selection is part of the method" testId="data-frame-detail"><p>End-diastolic and end-systolic frames were re-derived from segmentation masks because the resulting selection was more physiologically consistent on manual review. The choice was then tested in isolation as part of the robustness campaign.</p></DetailDisclosure></section>
    <NextPage to="/results" label="05 / The results" testId="data-next-results-link" /></div></ResearchLayout>;
}