import { ArrowUpRight, Check, Lightbulb, Scale, Target } from "lucide-react";
import ResearchLayout from "@/components/ResearchLayout";
import { NextPage, PageIntro, PaperCard, SectionLabel } from "@/components/ResearchPrimitives";

const findings = [{ title: "Parameter-efficient adaptation beats full fine-tuning on small clinical cohorts", text: "Full fine-tuning of the 89.5M-parameter backbone was consistently less accurate and far less stable than CC—LoRA's roughly 220K trainable parameters. Efficiency is a measured modelling advantage, not only a compute-saving convenience.", icon: Scale }, { title: "A handful of imaging-derived numbers carry most of the clinical signal", text: "Nine core imaging measurements outperformed the full 25-feature clinical set in the 3-class setting, replicated across four random seeds. Demographic and comorbidity features can add noise faster than signal on a cohort this size.", icon: Target }, { title: "Genetic-vs-phenotypic-mimic confusion is a known clinical phenomenon", text: "The pattern—hypertrophy causes blur together while Normal stays cleanly separable—was independently reported in a 23,745-patient echocardiography study, corroborating the model's failure mode rather than making it look like an artifact.", icon: Lightbulb }, { title: "Aggregate accuracy can hide the clinically important failure mode", text: "A simpler clinical-only model can match overall AUC while being dramatically worse at the hard cases. Per-class balance is essential when the errors have different clinical consequences.", icon: Check }];

export default function Findings() {
  return <ResearchLayout><div className="wide-wrap page-wrap"><PageIntro index="07" eyebrow="Key takeaways" title="What this project actually shows." description="Four findings sit underneath the headline metric. Together, they explain why the result matters beyond a single benchmark table."><div className="intro-meta"><span>INTERPRETATION</span><span>TRANSFERABLE PRINCIPLES</span><span>OPEN QUESTIONS</span></div></PageIntro>
    <section className="page-section" data-testid="findings-list-section"><div className="findings-list">{findings.map(({ title, text, icon: Icon }, index) => <PaperCard className="finding-row" key={title} testId={`finding-card-${index + 1}`}><div className="finding-number">0{index + 1}</div><div className="finding-icon"><Icon size={19} /></div><div className="finding-copy"><h2>{title}</h2><p>{text}</p></div><ArrowUpRight className="finding-arrow" size={18} /></PaperCard>)}</div></section>
    <section className="page-section tinted-block" data-testid="findings-implication-section"><div className="wide-wrap"><SectionLabel index="07.1">The broader implication</SectionLabel><div className="implication-grid"><div><h2>Multimodal context is most useful where visual evidence is underdetermined.</h2></div><div><p>The value of clinical data is not evenly distributed across every prediction. It appears where an image supports several plausible explanations and the patient's context can shift the prior. That is the design principle CC—LoRA makes concrete.</p><span className="principle-line"><i />Condition the representation at the point of ambiguity.</span></div></div></div></section>
    <section className="page-section" data-testid="findings-open-questions-section"><SectionLabel index="07.2">What comes next</SectionLabel><div className="questions-grid"><div><span>01</span><h3>Can this transfer across hospitals?</h3><p>Test whether the clinical embedding remains useful under scanner, protocol, and referral-population shift.</p></div><div><span>02</span><h3>Can the hard cases become interpretable?</h3><p>Connect adapter activation patterns to the measurements and history that change the differential.</p></div><div><span>03</span><h3>What is the right validation target?</h3><p>Move beyond AUC toward calibration, utility, and prospective clinician-in-the-loop evaluation.</p></div></div></section>
    <NextPage to="/about" label="08 / About the project" testId="findings-next-about-link" /></div></ResearchLayout>;
}