import { ArrowRight, BrainCircuit, CircleAlert, Stethoscope } from "lucide-react";
import ResearchLayout from "@/components/ResearchLayout";
import { Callout, DetailDisclosure, NextPage, PageIntro, PaperCard, SectionLabel } from "@/components/ResearchPrimitives";

export default function Problem() {
  return <ResearchLayout><div className="wide-wrap page-wrap"><PageIntro index="02" eyebrow="The clinical problem" title="One MRI finding. Several very different diagnoses." description="Left ventricular hypertrophy is a shared downstream phenotype. Distinguishing its cause is where imaging-only models—and often humans—start to struggle."><div className="intro-meta"><span>LVH DIFFERENTIAL DIAGNOSIS</span><span>4 CLASSES</span><span>SMALL-COHORT SETTING</span></div></PageIntro>
    <div className="problem-lead-grid"><PaperCard className="problem-statement" testId="problem-statement-card"><div className="large-quote" data-testid="problem-quote">“The same thickened ventricle can point to three different treatment paths.”</div><p data-testid="problem-statement-copy">Genetic hypertrophic cardiomyopathy, hypertensive HCM, and infiltrative amyloidosis can converge on a similar imaging phenotype. Normal anatomy is the easy negative class; the clinically important errors happen between the mimics.</p><div className="problem-markers"><span><CircleAlert size={16} />hard cases sit between disease classes</span><span><Stethoscope size={16} />clinical context changes the differential</span></div></PaperCard><div className="diagnosis-stack" data-testid="diagnosis-stack">{[{ icon: BrainCircuit, name: "Genetic HCM", note: "sarcomeric / inherited" }, { icon: Stethoscope, name: "Hypertensive HCM", note: "phenotypic mimic" }, { icon: CircleAlert, name: "Amyloidosis", note: "infiltrative disease" }].map(({ icon: Icon, name, note }, index) => <div className="diagnosis-item" key={name} data-testid={`diagnosis-item-${index + 1}`}><div className="diagnosis-icon"><Icon size={18} /></div><div><strong>{name}</strong><span>{note}</span></div><span className="diagnosis-similarity">≈</span></div>)}</div></div>
    <section className="page-section" data-testid="problem-why-section"><SectionLabel index="02.1">Why foundation models need help</SectionLabel><div className="two-column-copy"><div><h2>Strong on images. Blind to the chart.</h2><p>Cardiac MRI foundation models learn reusable visual representations from large imaging corpora. But clinical diagnosis is not an image-only task: age, comorbidities, measurements, and history all change how the same morphology should be interpreted.</p></div><div className="editorial-list"><div><span>01</span><p>Small hospital cohorts make full fine-tuning high variance and easy to overfit.</p></div><div><span>02</span><p>Labels encode a clinical differential that may not be visually separable.</p></div><div><span>03</span><p>Naive late fusion can add context without letting it shape visual reading.</p></div></div></div></section>
    <section className="page-section" data-testid="problem-pipeline-section"><SectionLabel index="02.2">The diagnostic tension</SectionLabel><PaperCard className="pipeline-card" testId="problem-pipeline-card"><div className="pipeline-row"><div className="pipeline-node"><span>IMAGE</span><strong>Cardiac MRI</strong><small>what the model sees</small></div><ArrowRight className="pipeline-arrow" size={21} /><div className="pipeline-node"><span>PHENOTYPE</span><strong>Thickened LV</strong><small>what overlaps</small></div><ArrowRight className="pipeline-arrow" size={21} /><div className="pipeline-node pipeline-highlight"><span>DIFFERENTIAL</span><strong>Which disease?</strong><small>where context matters</small></div></div><p className="pipeline-caption">The research target is not “does hypertrophy exist?” It is “what explains it in this patient?”</p></PaperCard></section>
    <section className="page-section" data-testid="problem-scope-section"><Callout tone="terracotta" testId="problem-scope-callout"><div><span className="callout-kicker">Scope of the thesis</span><p>The project focuses on adapting an existing cardiac MRI foundation model under a realistic data constraint: roughly 230 patients per training fold, a four-class clinical differential, and no permission to rewrite the backbone.</p></div></Callout><DetailDisclosure title="What counts as a clinically meaningful improvement?" testId="problem-definition-detail"><p>Not only a higher aggregate score. The evaluation looks for a more balanced separation of the three hypertrophy causes, while preserving the clean distinction between Normal and disease. That is why per-class recall, variance across folds, and error patterns matter alongside AUC.</p></DetailDisclosure></section>
    <NextPage to="/method" label="03 / The method" testId="problem-next-method-link" /></div></ResearchLayout>;
}