import { Check, FlaskConical, GitBranch, Sigma } from "lucide-react";
import ResearchLayout from "@/components/ResearchLayout";
import { Callout, NextPage, PageIntro, PaperCard, SectionLabel } from "@/components/ResearchPrimitives";

export default function Rigor() {
  return <ResearchLayout><div className="wide-wrap page-wrap"><PageIntro index="06" eyebrow="Scientific rigor" title="Built to survive scrutiny - not just look good in one table." description="The headline result was stress-tested through paired significance tests, multi-seed replication, and single-variable isolation ablations before it was treated as evidence."><div className="intro-meta"><span>5 FOLDS</span><span>4 RANDOM SEEDS</span><span>ISOLATION ABLATIONS</span></div></PageIntro>
    <section className="page-section" data-testid="rigor-evidence-section"><div className="evidence-grid"><PaperCard testId="rigor-significance-card"><div className="evidence-icon"><Sigma size={19} /></div><span className="evidence-status confirmed">CONFIRMED ROBUST</span><h3>Paired significance testing</h3><p>t-test and Wilcoxon tests across five folds. CC—LoRA's advantage over image-only-on-the-same-features is significant at <strong>p = 0.044</strong> and directionally consistent in every fold.</p></PaperCard><PaperCard testId="rigor-seeds-card"><div className="evidence-icon"><GitBranch size={19} /></div><span className="evidence-status confirmed">CONFIRMED ROBUST</span><h3>Multi-seed replication</h3><p>A surprising “imaging-only beats full feature set” result was re-run across four random seeds. It held every time, strongest on balanced accuracy.</p></PaperCard><PaperCard testId="rigor-isolation-card"><div className="evidence-icon terracotta"><FlaskConical size={19} /></div><span className="evidence-status qualified">CONFOUNDER RULED OUT</span><h3>Single-variable isolation</h3><p>Imputation strategy and ED/ES frame selection were each changed in isolation. Neither produced a statistically meaningful shift in the pipeline.</p></PaperCard></div></section>
    <section className="page-section" data-testid="rigor-matrix-section"><SectionLabel index="06.1">Evidence matrix</SectionLabel><PaperCard className="evidence-table-card" testId="rigor-evidence-table-card"><div className="table-wrap"><table data-testid="rigor-evidence-table"><thead><tr><th>Question</th><th>Test</th><th>Outcome</th></tr></thead><tbody><tr><td>Does clinical conditioning beat image-only LoRA?</td><td>Paired t-test + Wilcoxon</td><td><span className="table-outcome"><Check size={14} />p = 0.044</span></td></tr><tr><td>Is the feature-set surprise seed-dependent?</td><td>4-seed replication</td><td><span className="table-outcome"><Check size={14} />held in 4 / 4</span></td></tr><tr><td>Does frame selection change the result?</td><td>Single-variable isolation</td><td><span className="table-outcome neutral">no meaningful shift</span></td></tr></tbody></table></div></PaperCard></section>
    <section className="page-section" data-testid="rigor-limitations-section"><div className="two-column-copy"><div><SectionLabel index="06.2">Limitations</SectionLabel><h2>What the result does not claim.</h2><p>This is a single-hospital cohort with a small rare-disease class and a reconstructed confusion summary. The work demonstrates a promising adaptation strategy under constraint—not a finished clinical decision support tool.</p></div><Callout tone="terracotta" testId="rigor-limitations-callout"><div><span className="callout-kicker">Keep the result honest</span><p>External validation, calibration, prospective evaluation, and clinician-in-the-loop testing remain necessary before any real-world use.</p></div></Callout></div></section>
    <NextPage to="/findings" label="07 / Key findings" testId="rigor-next-findings-link" /></div></ResearchLayout>;
}